server:
  port: 8090
  
spring:
  application:
    name: apigateway
    
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#      - id: accountsservice
#        uri: lb://ACCOUNTSSERVICE
#        predicates:
#        - Path=/account/**
        
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
      
  instance:
    prefer-ip-address: true